<a href="https://colab.research.google.com/github/digvijaysingh21/AI_ML_Libraries_foundational/blob/main/numpy_2_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

#difference between list and numpy

li_arr = [i for i in range(0,100)] #list array
np_arr = np.arange(100) #numpy array

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [4]:
#size of one element in numpy array
print(np_arr.itemsize)

#size of 100 element in numpy array
print(np_arr.itemsize * np_arr.size)

8
800


In [10]:
import sys
#size of one element in list
a = 0;
print(sys.getsizeof(a))

#size of 100 elements in list
print(sys.getsizeof(a) * len(li_arr))

28
2800


**time execution of numpy is much faster then normal python list**

In [1]:
import time
import numpy as np

size = 100000

#add elements of array a and b

def addition_using_list():
  t1 = time.time()
  a = range(size)
  b = range(size)
  c = [a[i] + b[i] for i in range(size)]
  t2 = time.time()
  return (t2 - t1)


def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b
    t2 = time.time()
    return (t2 - t1)


t_list = addition_using_list()
print("List", t_list * 1000) #milliseconds
t_numpy = addition_using_numpy()
print('numpy', t_numpy * 1000)


List 22.62735366821289
numpy 5.028247833251953


In [2]:
import numpy as np

a = [1,2,3]
b = np.array(a)

print(b)
print(type(b))


[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1,2,3, '4', 'a', 4.5]
b = np.array(a)
print(b)

['1' '2' '3' '4' 'a' '4.5']


In [5]:
a=[1,2,3,'4','5'] #note if alpha value of string present and if be use dtype = int then it will throw error only numeric value of sting can be converted into dtype=int or float
b = np.array(a, dtype=int)
print(b)

[1 2 3 4 5]


In [6]:
b = np.array(a, dtype=float)
print(b)

[1. 2. 3. 4. 5.]


In [7]:
b = np.array(a, dtype=str)
print(b)

['1' '2' '3' '4' '5']


In [8]:
a = [1,2,3,'4','4.5']
b = np.array(a*3)
print(b)

['1' '2' '3' '4' '4.5' '1' '2' '3' '4' '4.5' '1' '2' '3' '4' '4.5']


In [11]:
b = np.ones(3, dtype=int) #by deafult it is float
print (b)

[1 1 1]


In [14]:
b = np.zeros(3)
print(b)

[0. 0. 0.]


In [18]:
b = np.ones((2,3),dtype=int) #2d array
print(b)

[[1 1 1]
 [1 1 1]]


In [21]:
b = np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
b = np.full(3, 5)
print(b)

[5 5 5]


In [26]:
b = np.full((3,3),5, dtype=float)
print(b)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [25]:
#numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.
b = np.empty(2, dtype=int)
print(b)

[-9093133594791772939      135431952875416]


In [27]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
b = np.arange(2,20,2)
print(b)

[ 2  4  6  8 10 12 14 16 18]


In [31]:
b = np.linspace(2, 10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [32]:
b = np.linspace(2, 10, 5, dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [35]:
b = np.linspace(2,10,5, endpoint = False, dtype=int)
b

array([2, 3, 5, 6, 8])

In [36]:
b = np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
b = np.eye(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
b = np.eye(3,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
b = np.random.rand(3)
b

array([0.45979698, 0.47903395, 0.84279065])

In [50]:
b = np.random.rand(2,3)
b

array([[0.84102837, 0.67234087, 0.29066657],
       [0.9478477 , 0.6903801 , 0.43833411]])

In [52]:
b = np.random.rand(10)*10
b

array([0.67632684, 5.15736588, 5.944525  , 4.57674628, 1.58722255,
       0.18658046, 9.93074071, 2.04927788, 8.26102948, 0.77216186])