<a href="https://colab.research.google.com/github/digvijaysingh21/AI_ML_Libraries_foundational/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
#creating 1 d array
arr1d = np.array([1,2,3,4])
print("1d array", arr1d)

1d array [1 2 3 4]


In [7]:
#creating 2d array
arr2d = np.array([[1,2,3],[4,5,6]])
print("2d array", arr2d)

2d array [[1 2 3]
 [4 5 6]]


In [8]:
#array of zeros
zeros = np.zeros((2,3))
print("zeros array", zeros)

zeros array [[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#array of ones
one = np.ones([3,3])
print("all ones", one)

all ones [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# array with range of values
range_array = np.arange(1,10,2)
print("Range arrays", range_array)

Range arrays [1 3 5 7 9]


In [15]:
# np.arange([start, ]stop, [step, ], dtype=None)

# start (optional): The starting value of the sequence. Default is 0 if not provided.
# stop: The value at which to stop (but this value is not included in the result).
# step (optional): The step size between each value. Default is 1 if not provided.
# dtype (optional): The data type of the resulting array.
ans = np.arange(5)
print(ans)


[0 1 2 3 4]


In [18]:

# res = np.arange(1,10,dtype=float)
res = np.arange(1,10,1.5,dtype=float)
print(res)

[1.  2.5 4.  5.5 7.  8.5]


In [21]:
#Creates an identity matrix.
result = np.eye(3)
print(result)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
#Flattens a multi-dimensional array into a 1D array.
answer = np.array([[1,2,3],[4,5,6]])
arr_flat = answer.flatten()
print(arr_flat)

[1 2 3 4 5 6]


In [25]:
#np.add(), np.subtract(), np.multiply(), np.divide(): Perform element-wise addition, subtraction, multiplication, and division.
answer1 = np.array([1,2,3])
answer2 = np.array([4,5,6])
result = np.add(answer1, answer2)
print(result)

[5 7 9]


In [27]:
#Computes the sum of array elements.
res = np.array([1,2,3])
ans = res.sum()
print(ans)

6
